name: Build and upload to PyPI

on: [push, pull_request]

jobs:
  build_windows_wheel:
    name: Build wheel on Windows
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13'] 

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Build Windows wheel
        run: python setup.py bdist_wheel -d wheelhouse

      - name: Upload Windows wheels
        uses: actions/upload-artifact@v4
        with:
          name: windows-wheels-${{ matrix.python-version }}
          path: wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools

      - name: Build source distribution
        run: python setup.py sdist -d dist

      - name: Upload source distribution
        uses: actions/upload-artifact@v4
        with:
          name: source-distribution
          path: dist/*.tar.gz

  upload_pypi:
    needs: [build_windows_wheel, build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
          skip_existing: true
